name: pdam_fields
description: "TKR Field Ops — Aplikasi internal PDAM untuk petugas lapangan"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Navigation
  go_router: ^14.3.0

  # Dependency Injection
  get_it: ^7.7.0

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Local Storage (Offline-First)
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2

  # Utilities
  intl: any
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
